theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 400

[[block]]
block = "load"
format = "{1m}"
interval = 60

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
interval = 5

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
max_ssid_width = 12
interval = 5

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"

[[block]]
block = "time"
format = "%a %m/%d %H:%M:%S"
interval = 1
