#!/bin/sh

bspc monitor -d www edit code terminal file mail slack media keepass vm

bspc config border_width 2
bspc config window_gap 2
bspc config top_padding 48

bspc config focus_follows_pointer true
bspc config click_to_focus false

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 move
bspc config pointer_action3 resize_corner

bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true

bspc config active_border_color "#FF0000"
bspc config focused_border_color "#FF9500"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# Window quirks
bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a Firefox desktop='^1'
bspc rule -a Emacs desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Boostnote desktop='^3'
bspc rule -a URxvt desktop='^4'
bspc rule -a Mate-terminal desktop='^4'
bspc rule -a Gnome-terminal desktop='^4'
bspc rule -a Thunar desktop='^5'
bspc rule -a Slack desktop='^7'
bspc rule -a Eom desktop='^8'
bspc rule -a Gom desktop='^8'
bspc rule -a Abiword desktop='^8'
bspc rule -a 'Google Play Music Desktop Player' desktop='^8'
bspc rule -a keepassxc desktop='^9'
bspc rule -a VirtualBox desktop='^10'
bspc rule -a Chromium desktop='^10'
bspc rule -a Qemu-system-x86_64 desktop='^10' state=floating rectangle=1920x1200+0+24
bspc rule -a Vncviewer desktop='^10' state=floating rectangle=1920x1200+0+24
bspc rule -a Spicy desktop='^10' state=floating rectangle=1920x1248+0+24
bspc rule -a Screenkey manage=off

pacmd unload-module module-suspend-on-idle

/usr/bin/xrdb ~/.Xresources
/usr/bin/xrdb -merge ~/.Xresources.hidpi
/usr/bin/setxkbmap -option ctrl:nocaps
/usr/bin/sxhkd &
/usr/bin/dunst &
/usr/bin/dex -a -s "/home/i2tsuki/.config/autostart" &
/usr/bin/nm-applet &
/usr/bin/gnome-flashback &
/usr/bin/conky &
/usr/bin/compton &
/usr/bin/xsetroot -cursor_name left_ptr
/usr/bin/xset s 300 5
/usr/bin/gnome-panel &
/usr/bin/fcitx -d
