#!/bin/sh

bspc monitor -d www edit code terminal file mail slack media keepass vm

bspc config border_width 2
bspc config window_gap 6

bspc config focus_follows_pointer true
bspc config pointer_modifier mod4

bspc config active_border_color "#FF0000"
bspc config focused_border_color "#FF9500"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# Window quirks
bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a Firefox desktop='^1'
bspc rule -a Emacs desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Boostnote desktop='^3'
bspc rule -a URxvt desktop='^4'
bspc rule -a Thunar desktop='^5'
bspc rule -a Thunderbird desktop='^6'
bspc rule -a Slack desktop='^7'
bspc rule -a Eom desktop='^8'
bspc rule -a 'Google Play Music Desktop Player' desktop='^8'
bspc rule -a Keepassxc desktop='^9'
bspc rule -a VirtualBox desktop='^10'
bspc rule -a Chromium desktop='^10'

bspc rule -a Screenkey manage=off

/usr/bin/polybar top &
/usr/bin/compton &
/usr/bin/nitrogen --restore &
/usr/lib64/xfce4/notifyd/xfce4-notifyd &

/usr/bin/dex -a -s "/home/kizkoh/.config/autostart" &
/home/kizkoh/.local/bin/dropbox &
/home/kizkoh/.local/bin/mpdcover &
/usr/bin/conky -c ~/.conkyrc &
/usr/bin/mpd
https://03fa60003bbf4a31a999ea8f03879084.vfs.cloud9.us-east-1.amazonaws.com/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
