#!/bin/sh

bspc monitor -d www edit code terminal file mail slack media keepass vm

bspc config border_width 2
bspc config window_gap 7

bspc config focus_follows_pointer true
bspc config click_to_focus false

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 move
bspc config pointer_action3 resize_corner

bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true

bspc config active_border_color "#FF0000"
bspc config focused_border_color "#FF9500"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# Window quirks
bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a Firefox desktop='^1'
bspc rule -a Emacs desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Boostnote desktop='^3'
bspc rule -a URxvt desktop='^4'
bspc rule -a Mate-terminal desktop='^4'
bspc rule -a Thunar desktop='^5'
bspc rule -a Thunderbird desktop='^6'
bspc rule -a Slack desktop='^7'
bspc rule -a Eom desktop='^8'
bspc rule -a Franz desktop='^8'
bspc rule -a 'Google Play Music Desktop Player' desktop='^8'
bspc rule -a keepassxc desktop='^9'
bspc rule -a VirtualBox desktop='^10'
bspc rule -a Chromium desktop='^10'
bspc rule -a Qemu-system-x86_64 desktop='^10' state=floating rectangle=1920x1200+0+24
bspc rule -a Vncviewer desktop='^10' state=floating rectangle=1920x1200+0+24
bspc rule -a Spicy desktop='^10' state=floating rectangle=1920x1248+0+24

bspc rule -a Screenkey manage=off

/usr/bin/polybar top &
/usr/bin/compton &
/usr/bin/nitrogen --restore &

/usr/bin/dex -a -s "/home/kizkoh/.config/autostart" &
/usr/bin/dunst &
/opt/bin/dropbox &
/usr/bin/conky -c ~/.conkyrc
/usr/bin/xset s 300 5
/usr/bin/xss-lock -n /usr/bin/xtrlock xtrlock
